spring:
  application:
    name: mail-service
  kafka:
    bootstrap-servers: broker:29092
    consumer:
      group-id: client-mail-service-group
      keyDeserializer: "org.apache.kafka.common.serialization.StringDeserializer"
      valueDeserializer: "io.confluent.kafka.serializers.KafkaAvroDeserializer"
      properties:
        schema:
          registry:
            url: http://schema-registry:8081
        specific:
          avro:
            reader: "true"  
mail:
  host: smtp.mail.ru
  port: 465
  username: ${MAIL_USER}
  password: ${MAIL_PASSWORD}
  properties:
    mail:
      smtps:
        starttls:
          enable: true
          required: true
        auth: true
        ssl: trust:smtp.mail.ru
  protocol: smtps
  
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://discovery-server:8761/eureka

kafka:
  topic:
    verification: verification_topic
avro:
  topic:
    name:
      verification: verification_topic

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health, info


