spring:
  application:
    name: money-transfer-service

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://database-money-transfer-service:5432/postgres
    username: postgres
    password: root

  liquibase:
    enabled: true

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
  kafka:
    bootstrap-servers: broker:29092
    producer:
      keySerializer: "org.apache.kafka.common.serialization.StringSerializer"
      valueSerializer: "io.confluent.kafka.serializers.KafkaAvroSerializer"
      properties:
        schema:
          registry:
            url: http://schema-registry:8081
    consumer:
      group-id: money-transfer-service
      keyDeserializer: "org.apache.kafka.common.serialization.StringDeserializer"
      valueDeserializer: "io.confluent.kafka.serializers.KafkaAvroDeserializer"
      properties:
        schema:
          registry:
            url: http://schema-registry:8081
        specific:
          avro:
            reader: "true"
kafka:
  topic:
    transaction: transaction_broker
avro:
  topic:
    name:
      transaction: transaction_broker
      transfer: transfer_broker

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://discovery-server:8761/eureka
openapi:
  service:
    version: 1.0.0
    name: ${spring.application.name}
    description: "Responsible for managing funds transfers" #api gateway url
    url: http://localhost:8072
springdoc:
  api-docs:
    path: /money-transfer-service/v3/api-docs #these urls will used to load the swagger ui of this service by the api gateway
  swagger-ui:
    path: /money-transfer-service/swagger-ui.html


resilience4j:
  timelimiter:
    configs:
      default:
        timeout-duration: 3s

---

management:
  endpoints:
    web:
      exposure:
        include: '*'
  health.circuitbreakers.enabled: true
