spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://database-user-service:5432/postgres
    username: postgres
    password: root
    
  liquibase:
    enabled: true

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://discovery-server:8761/eureka
